export enum PATHROUTES {
  LOGIN = "/",
  HOME = "/in",
  LIST = "/in/users/list",
  USER = "/in/users",
  CREATE_USER = "/in/users/create",
  UPDATE_USER = "/in/users/edit",
  MY_ACCOUNT = "/in/users/me",
  COMPANY = "/in/company",
  LIST_COMPANY = "/in/company/list",
  CREATE_COMPANY = "/in/company/create",
  UPDATE_COMPANY = "/in/company/update",
  MAITENANCE = "/in/maitenance",
  DELIVERABLES = "/in/deliverables",
  INVOICES = "/in/invoices",
  INVOICES_LIST = "/in/invoices/list",
  UPLOAD_INVOICES = "/in/invoices/upload",
  UPDATE_INVOICES = "/in/invoices/edit",
}
