export enum PATHROUTES {
  LOGIN = "/",
  HOME = "/in",
  CREATE_USER = "/in/create-user",
  UPDATE_USER = "/in/update-user",
  LIST = "/in/list",
  CREATE_COMPANY = "/in/company/create",
  UPDATE_COMPANY = "/in/company/update",
  LIST_COMPANY = "/in/company/list",
  MY_ACCOUNT = "/in/my-account",
  MAITENANCE = "/in/maitenance",
  DELIVERABLES = "/in/deliverables",
  INVOICES = "/in/list-invoices",
  UPLOAD_INVOICES = "/in/upload-invoices",
  UPDATE_INVOICES = "/in/update-invoice",
}
