import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/dashboard/Sidebar";
import Notifications from "@/components/ButtonAlerts/ButtonAlerts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bp Ventures Panel Control",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

  <div className={inter.className}>
    <div className="relative flex">
      <Sidebar />
      
      <div className="absolute top-0 right-0 mt-4 mr-4 z-10">
        <Notifications />
      </div>

      <div className="flex-1 overflow-x-auto">
        {children}
      </div>
    </div>
  </div>
  );
}
